### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by pavanagrawal123** [jsonmaur/robinhood-web#2]
Hi!

Just found this and looks awesome!

Does this currently work? Is it pulling info from the API, or just using dummy data?

Thanks!

**Comment by jsonmaur** [comment]
Thanks! It just uses dummy data, no real uses for now.

**Comment by pavanagrawal123** [comment]
How difficult do you think adding in API usage would be? 

If I have some extra time, I can try implementing it.

**Comment by jsonmaur** [comment]
I never really planned on taking it much further than it is. But if you want to take a shot at it, feel free! I don't think Robinhood has a public API, but if you can find a good data source it wouldn't be too bad to implement. There's no state management other than React, but you could use Redux without much trouble.

**Comment by bggardner** [comment]
This does look awesome, and [here's](https://github.com/sanko/Robinhood) a good API reference.  Also, the code that [hoodtrader.com](https://hoodtrader.com) uses would be a good starting point.  Good luck.

**Comment by eugv86** [comment]
Jason, I actually created a web platform for Robinhood and used a little of your friends design.  Check it out... 
https://github.com/eugv86/Robinhood-Ninja 

https://robinhoodninja.com
